### ISSUE TITLE
Autoloader calls die(), causes problems with Rector

### ISSUE THREAD

**Issue by jlherren** [apereo/phpCAS#374]
I started using [Rector](https://github.com/rectorphp/rector#rector---speedup-your-php-development) to automatically fix issues in my code, however it dies on this line:

    phpCAS::client(CAS_VERSION_3_0, $host, $port, $path, false);

For reasons unknown to me Rector (or rather the bundled PHPStan) attempts to resolve `CAS_VERSION_3_0` as a class and tries to autoload it.  However, phpCAS' autoloader obviously can't find such a class, then makes an attempt to detect whether it is inside a `class_exists()` or `interface_exists()` and [simply calls die()](https://github.com/apereo/phpCAS/blob/2d3c6b5cb8a5c85c1c0b7ea20195e6515fc845bb/source/CAS/Autoload.php#L80) when it finds that this is not the case.

Looking at the stack trace (see below), this happens inside a call to `trait_exists()`, which is obviously not detected.

Two options:
- add a check also for `trait_exists()`, or
- consider replacing `die()` with `return false;` (at first sight, dying looks like very bad practice)

Unfortunately, I have so far been unable to construct a small test case, but in case it's of interest, here's the full error I got:

```
$ vendor/bin/rector process src --dry-run
 120/488 [▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░]  24%Exception: Class CAS_VERSION_3_0 could not be loaded from /path/to/project/vendor/apereo/phpcas/source/../test//CAS/VERSION/3/0.php, file does not exist (Path="/path/to/project/vendor/apereo/phpcas/source:/path/to/project/vendor/apereo/phpcas/source/../test/") [CAS_autoload] in /path/to/project/vendor/apereo/phpcas/source/CAS/Autoload.php:57
Stack trace:
#0 [internal function]: CAS_autoload('CAS_VERSION_3_0')
#1 [internal function]: spl_autoload_call('CAS_VERSION_3_0')
#2 phar:///path/to/project/vendor/rector/rector-prefixed/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/Runtime/RuntimeReflectionProvider.php(137): trait_exists('CAS_VERSION_3_0')
#3 phar:///path/to/project/vendor/rector/rector-prefixed/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/ClassBlacklistReflectionProvider.php(40): PHPStan\Reflection\Runtime\RuntimeReflectionProvider->hasClass('CAS_VERSION_3_0')
#4 phar:///path/to/project/vendor/rector/rector-prefixed/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/ChainReflectionProvider.php(25): PHPStan\Reflection\ReflectionProvider\ClassBlacklistReflectionProvider->hasClass('CAS_VERSION_3_0')
#5 phar:///path/to/project/vendor/rector/rector-prefixed/vendor/phpstan/phpstan/phpstan.phar/src/Reflection/ReflectionProvider/MemoizingReflectionProvider.php(31): PHPStan\Reflection\ReflectionProvider\ChainReflectionProvider->hasClass('CAS_VERSION_3_0')
#6 /path/to/project/vendor/rector/rector-prefixed/rules/CodeQuality/Rector/Name/FixClassCaseSensitivityNameRector.php(76): PHPStan\Reflection\ReflectionProvider\MemoizingReflectionProvider->hasClass('CAS_VERSION_3_0')
#7 /path/to/project/vendor/rector/rector-prefixed/src/Rector/AbstractRector.php(245): Rector\CodeQuality\Rector\Name\FixClassCaseSensitivityNameRector->refactor(Object(PhpParser\Node\Name))
#8 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): Rector\Core\Rector\AbstractRector->enterNode(Object(PhpParser\Node\Name))
#9 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\ConstFetch))
#10 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Arg))
#11 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#12 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\StaticCall))
#13 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Expression))
#14 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#15 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\ClassMethod))
#16 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#17 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Class_))
#18 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#19 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#20 /path/to/project/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#21 /path/to/project/vendor/rector/rector-prefixed/src/PhpParser/NodeTraverser/RectorNodeTraverser.php(46): PhpParser\NodeTraverser->traverse(Array)
#22 /path/to/project/vendor/rector/rector-prefixed/src/Application/FileProcessor.php(53): Rector\Core\PhpParser\NodeTraverser\RectorNodeTraverser->traverse(Array)
#23 /path/to/project/vendor/rector/rector-prefixed/src/Application/FileProcessor/PhpFileProcessor.php(175): Rector\Core\Application\FileProcessor->refactor(Object(Rector\Core\ValueObject\Application\File))
#24 /path/to/project/vendor/rector/rector-prefixed/src/Application/FileProcessor/PhpFileProcessor.php(188): Rector\Core\Application\FileProcessor\PhpFileProcessor->Rector\Core\Application\FileProcessor\{closure}(Object(Rector\Core\ValueObject\Application\File))
#25 /path/to/project/vendor/rector/rector-prefixed/src/Application/FileProcessor/PhpFileProcessor.php(176): Rector\Core\Application\FileProcessor\PhpFileProcessor->tryCatchWrapper(Object(Rector\Core\ValueObject\Application\File), Object(Closure), 'refactoring')
#26 /path/to/project/vendor/rector/rector-prefixed/src/Application/FileProcessor/PhpFileProcessor.php(118): Rector\Core\Application\FileProcessor\PhpFileProcessor->refactorNodesWithRectors(Array)
#27 /path/to/project/vendor/rector/rector-prefixed/src/Application/ApplicationFileProcessor.php(57): Rector\Core\Application\FileProcessor\PhpFileProcessor->process(Array)
#28 /path/to/project/vendor/rector/rector-prefixed/src/Application/ApplicationFileProcessor.php(44): Rector\Core\Application\ApplicationFileProcessor->processFiles(Array)
#29 /path/to/project/vendor/rector/rector-prefixed/src/Console/Command/ProcessCommand.php(134): Rector\Core\Application\ApplicationFileProcessor->run(Array)
#30 /path/to/project/vendor/rector/rector-prefixed/vendor/symfony/console/Command/Command.php(230): Rector\Core\Console\Command\ProcessCommand->execute(Object(RectorPrefix20210424\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210424\Symfony\Component\Console\Output\ConsoleOutput))
#31 /path/to/project/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php(826): RectorPrefix20210424\Symfony\Component\Console\Command\Command->run(Object(RectorPrefix20210424\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210424\Symfony\Component\Console\Output\ConsoleOutput))
#32 /path/to/project/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php(251): RectorPrefix20210424\Symfony\Component\Console\Application->doRunCommand(Object(Rector\Core\Console\Command\ProcessCommand), Object(RectorPrefix20210424\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210424\Symfony\Component\Console\Output\ConsoleOutput))
#33 /path/to/project/vendor/rector/rector-prefixed/src/Console/ConsoleApplication.php(72): RectorPrefix20210424\Symfony\Component\Console\Application->doRun(Object(RectorPrefix20210424\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210424\Symfony\Component\Console\Output\ConsoleOutput))
#34 /path/to/project/vendor/rector/rector-prefixed/vendor/symfony/console/Application.php(152): Rector\Core\Console\ConsoleApplication->doRun(Object(RectorPrefix20210424\Symfony\Component\Console\Input\ArgvInput), Object(RectorPrefix20210424\Symfony\Component\Console\Output\ConsoleOutput))
#35 /path/to/project/vendor/rector/rector-prefixed/bin/rector.php(44): RectorPrefix20210424\Symfony\Component\Console\Application->run()
#36 /path/to/project/vendor/rector/rector-prefixed/bin/rector(5): require_once('/path/to/project/...')
#37 {main}
```

**Comment by jfritschi** [comment]
I guess no one has any experience with Rector.... Does the problem still exist?
